const fs = require('fs');

const categories = {
    "Alimentation": [
        { title: "0g de viande rouge", points: 40 },
        { title: "Faire un repas 100% végétarien", points: 20 },
        { title: "Acheter des fruits/légumes de saison", points: 20 },
        { title: "Manger local (produits < 100km)", points: 40 },
        { title: "Cuisiner avec les restes", points: 10 },
        { title: "Ne pas gaspiller de nourriture", points: 20 },
        { title: "Faire son propre pain", points: 50 },
        { title: "Faire un gâteau maison", points: 20 },
        { title: "Acheter en vrac", points: 30 },
        { title: "Boire de l'eau du robinet", points: 10 },
        { title: "Éviter les produits transformés", points: 40 },
        { title: "Cuisiner une recette végétalienne", points: 40 },
        { title: "Préparer sa lunchbox", points: 30 },
        { title: "Composter ses déchets organiques", points: 50 },
        { title: "Consommer des protéines végétales", points: 20 },
        { title: "Découvrir une nouvelle légumineuse", points: 20 },
        { title: "Acheter au marché local", points: 40 },
        { title: "Ne pas acheter de bouteille en plastique", points: 20 },
        { title: "Consommer un fruit en dessert", points: 10 },
        { title: "Faire son propre lait végétal", points: 50 },
        { title: "Manger des noix/graines au goûter", points: 10 },
        { title: "Refuser un emballage alimentaire", points: 20 },
        { title: "Prendre un café sans gobelet jetable", points: 10 },
        { title: "Acheter un produit imparfait/moche", points: 10 },
        { title: "Faire une soupe anti-gaspi", points: 30 },
        { title: "Tester le tofu ou le seitan", points: 20 },
        { title: "Préparer le menu de la semaine à l'avance", points: 30 },
        { title: "Congeler des aliments avant qu'ils périssent", points: 20 },
        { title: "Acheter un produit certifié bio", points: 20 },
        { title: "Réduire sa consommation de fromage", points: 30 }
    ],
    "Transport": [
        { title: "Utiliser les transports en commun", points: 20 },
        { title: "Aller au travail/école à vélo", points: 40 },
        { title: "Marcher au lieu de prendre la voiture", points: 30 },
        { title: "Faire du covoiturage", points: 40 },
        { title: "Télétravailler si possible", points: 50 },
        { title: "Privilégier le train à la voiture", points: 50 },
        { title: "Utiliser le train pour un trajet long", points: 40 },
        { title: "Prendre les escaliers au lieu de l'ascenseur", points: 10 },
        { title: "Optimiser ses déplacements en une seule sortie", points: 20 },
        { title: "Essayer un nouveau mode de transport doux", points: 40 },
        { title: "Regonfler les pneus de son vélo", points: 20 },
        { title: "Conduire en éco-conduite", points: 30 },
        { title: "Couper le moteur à l'arrêt", points: 10 },
        { title: "Vérifier la pression des pneus (voiture)", points: 20 },
        { title: "Ne pas utiliser la climatisation en voiture", points: 20 },
        { title: "Entretenir son vélo", points: 20 },
        { title: "Partager son trajet sur une application", points: 50 },
        { title: "Marcher au moins 5000 pas", points: 30 },
        { title: "Prendre le métro/tram", points: 20 },
        { title: "Aller faire ses courses à pied", points: 30 },
        { title: "Laisser la voiture au garage", points: 40 },
        { title: "Voyager léger", points: 20 },
        { title: "Organiser un trajet à plusieurs", points: 50 },
        { title: "Privilégier les visios", points: 10 },
        { title: "Éviter les détours inutiles", points: 10 },
        { title: "Conduire à 110 km/h max sur autoroute", points: 30 },
        { title: "Planifier des vacances sans avion", points: 50 },
        { title: "Utiliser une trottinette pour un court trajet", points: 20 },
        { title: "Rejoindre un groupe de covoiturage domicile-travail", points: 40 },
        { title: "Couper la climatisation avant d'arriver à destination", points: 10 }
    ],
    "Énergie": [
        { title: "Éteindre les appareils en veille", points: 20 },
        { title: "Réduire la température de 1°C", points: 40 },
        { title: "Éteindre la box internet la nuit", points: 10 },
        { title: "Prendre une douche de moins de 5 minutes", points: 30 },
        { title: "Laver son linge à 30°C", points: 20 },
        { title: "Faire sécher le linge à l'air libre", points: 20 },
        { title: "Dégivrer le congélateur/frigo", points: 50 },
        { title: "Mettre un couvercle pour bouillir de l'eau", points: 10 },
        { title: "Privilégier la lumière naturelle", points: 10 },
        { title: "Remplacer une ampoule par une LED", points: 30 },
        { title: "Ne pas allumer la climatisation", points: 30 },
        { title: "Éteindre la multiprise le soir", points: 10 },
        { title: "Charger son téléphone en mode avion", points: 10 },
        { title: "Ne garder que les mails importants", points: 20 },
        { title: "Baisser la luminosité de ses écrans", points: 10 },
        { title: "Fermer les volets la nuit pour isoler", points: 20 },
        { title: "Éteindre la lumière en quittant une pièce", points: 10 },
        { title: "Utiliser le mode éco du lave-vaisselle", points: 20 },
        { title: "Attendre que le lave-vaisselle soit plein", points: 20 },
        { title: "Optimiser le rangement du frigo", points: 40 },
        { title: "Penser à purger les radiateurs", points: 50 },
        { title: "Regarder des vidéos en basse résolution", points: 20 },
        { title: "Se désabonner de 5 newsletters", points: 30 },
        { title: "Fermer les onglets inactifs", points: 10 },
        { title: "Nettoyer les filtres de ses appareils", points: 40 },
        { title: "Faire une lessive à pleine charge uniquement", points: 20 },
        { title: "Débrancher les chargeurs non utilisés", points: 10 },
        { title: "Limiter l'usage du sèche-cheveux", points: 20 },
        { title: "Installer un économiseur d'eau sur le robinet", points: 40 },
        { title: "Faire un bilan de sa consommation énergétique", points: 40 }
    ],
    "Consommation": [
        { title: "Zéro plastique à usage unique", points: 50 },
        { title: "Utiliser une gourde", points: 10 },
        { title: "Acheter un vêtement de seconde main", points: 40 },
        { title: "Refuser un ticket de caisse", points: 10 },
        { title: "Donner un objet non utilisé", points: 30 },
        { title: "Réparer un objet au lieu de jeter", points: 50 },
        { title: "Faire son propre produit d'entretien", points: 50 },
        { title: "Utiliser un sac en tissu pour les courses", points: 10 },
        { title: "Refuser les goodies inutiles", points: 20 },
        { title: "Acheter un livre d'occasion", points: 30 },
        { title: "Utiliser un savon solide", points: 20 },
        { title: "Utiliser un shampoing solide", points: 20 },
        { title: "Utiliser des carrés démaquillants lavables", points: 20 },
        { title: "Emballer un cadeau avec du tissu", points: 40 },
        { title: "Éviter la fast-fashion", points: 50 },
        { title: "Emprunter à la bibliothèque", points: 30 },
        { title: "Louer un outil plutôt que l'acheter", points: 40 },
        { title: "Mettre un stop-pub sur sa boîte", points: 20 },
        { title: "Recycler un déchet électronique", points: 30 },
        { title: "Trier tous ses emballages", points: 20 },
        { title: "Réutiliser un bocal en verre", points: 10 },
        { title: "Construire/Réaliser un objet soi-même", points: 50 },
        { title: "Participer à une brocante", points: 40 },
        { title: "Nettoyer sa boîte mail (supprimer 50 mails)", points: 30 },
        { title: "Acheter un appareil électronique reconditionné", points: 40 },
        { title: "Échanger un objet avec un voisin ou un ami", points: 30 },
        { title: "Comparer l'impact carbone avant un achat", points: 20 },
        { title: "Choisir la livraison lente ou groupée", points: 20 },
        { title: "Utiliser un filtre à eau plutôt que des bouteilles", points: 30 },
        { title: "Trier et donner ses vêtements au lieu de jeter", points: 30 }
    ]
};

let idCount = 1;
const all = [];

for (const [cat, items] of Object.entries(categories)) {
    for (const item of items) {
        all.push({
            id: idCount++,
            title: item.title,
            points: item.points,
            category: cat
        });
    }
}

fs.mkdirSync('./src/data', { recursive: true });
fs.writeFileSync('./src/data/challenges.json', JSON.stringify(all, null, 2));
console.log('100 défis ont été générés dans src/data/challenges.json avec leurs points par difficulté.');